// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressInputController from "./address_input_controller"
application.register("address-input", AddressInputController)

import FilterVideosController from "./filter_videos_controller"
application.register("filter-videos", FilterVideosController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LanesGoogleMapsController from "./lanes_google_maps_controller"
application.register("lanes-google-maps", LanesGoogleMapsController)

import LanesNewGoogleMapsController from "./lanes_new_google_maps_controller"
application.register("lanes-new-google-maps", LanesNewGoogleMapsController)

import LanguageController from "./language_controller"
application.register("language", LanguageController)

import LikeDropdownsController from "./like_dropdowns_controller"
application.register("like-dropdowns", LikeDropdownsController)

import LikedLanesMapController from "./liked_lanes_map_controller"
application.register("liked-lanes-map", LikedLanesMapController)

import LikedRacksMapController from "./liked_racks_map_controller"
application.register("liked-racks-map", LikedRacksMapController)

import LikedShopsMapController from "./liked_shops_map_controller"
application.register("liked-shops-map", LikedShopsMapController)

import NotificationFadeController from "./notification_fade_controller"
application.register("notification-fade", NotificationFadeController)

import ProfileMapsController from "./profile_maps_controller"
application.register("profile-maps", ProfileMapsController)

import RacksGoogleMapsController from "./racks_google_maps_controller"
application.register("racks-google-maps", RacksGoogleMapsController)

import SearchAddressController from "./search_address_controller"
application.register("search-address", SearchAddressController)

import ShopsGoogleMapsController from "./shops_google_maps_controller"
application.register("shops-google-maps", ShopsGoogleMapsController)
